export interface UserGithubAccount {
  login: string;
  id: number;
  node_id: string;
  avatar_url: string;
  gravatar_id: string;
  url: string;
  html_url: string;
  followers_url: string;
  following_url: string;
  gists_url: string;
  starred_url: string;
  subscriptions_url: string;
  organizations_url: string;
  repos_url: string;
  events_url: string;
  received_events_url: string;
  type: string;
  site_admin: boolean;
  name: string;
  company: string;
  blog: string;
  location: string;
  email: string;
  hireable: string;
  bio: string;
  twitter_username: string;
  public_repos: number;
  public_gists: number;
  followers: number;
  following: number;
  created_at: string;
  updated_at: string;
}

export class ClassUserGithubAccount {
  login?: string;
  id?: number;
  node_id?: string;
  avatar_url?: string;
  gravatar_id?: string;
  url?: string;
  html_url?: string;
  followers_url?: string;
  following_url?: string;
  gists_url?: string;
  starred_url?: string;
  subscriptions_url?: string;
  organizations_url?: string;
  repos_url?: string;
  events_url?: string;
  received_events_url?: string;
  type?: string;
  site_admin?: boolean;
  name?: string;
  company?: string;
  blog?: string;
  location?: string;
  email?: string;
  hireable?: string;
  bio?: string;
  twitter_username?: string;
  public_repos?: number;
  public_gists?: number;
  followers?: number;
  following?: number;
  created_at?: string;
  updated_at?: string;

  public constructor(options: UserGithubAccount) {
    this.login = options.login;
    this.id = options.id;
    this.node_id = options.node_id;
    this.avatar_url = options.avatar_url;
    this.gravatar_id = options.gravatar_id;
    this.url = options.url;
    this.html_url = options.html_url;
    this.followers_url = options.followers_url;
    this.following_url = options.following_url;
    this.gists_url = options.gists_url;
    this.starred_url = options.starred_url;
    this.subscriptions_url = options.subscriptions_url;
    this.organizations_url = options.organizations_url;
    this.repos_url = options.repos_url;
    this.events_url = options.events_url;
    this.received_events_url = options.received_events_url;
    this.type = options.type;
    this.site_admin = options.site_admin;
    this.name = options.name;
    this.company = options.company;
    this.blog = options.blog;
    this.location = options.location;
    this.email = options.email;
    this.hireable = options.hireable;
    this.bio = options.bio;
    this.twitter_username = options.twitter_username;
    this.public_repos = options.public_repos;
    this.public_gists = options.public_gists;
    this.followers = options.followers;
    this.following = options.following;
    this.created_at = options.created_at;
    this.updated_at = options.updated_at;
  }
}
